version: '2'
services:
  node:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      PORT: 8080
    networks:
      - back
    restart: unless-stopped
    volumes:
      - .:/app
    command: npm run start:dev
    image: shadezp/node

  postgres:
    build: ./database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - back
    restart: unless-stopped
    image: shadezp/postgres

networks:
  back:
