version: '2'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      PORT: ${PORT}
    networks:
      - back
    restart: unless-stopped
    volumes:
      - .:/app
    command: npm run start:dev
    image: shadezp/node

  postgres:
    build: ./database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - back
    restart: unless-stopped
    image: shadezp/postgres

networks:
  back:
