version: '2'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgresDB
    environment:
      PORT: ${PORT}
    networks:
      - back
    restart: unless-stopped
    volumes:
      - .:/app
    command: npm run start:dev
    image: shadezp/node

  postgresDB:
    build: ./database
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    networks:
      - back
    restart: unless-stopped
    image: shadezp/postgres

networks:
  back:
